### ISSUE TITLE
Add ability to specify snmp config for network nodes

### ISSUE THREAD

**Issue by jonstout** [GlobalNOC/VCE#258]
Add ability to specify snmp community string for network nodes. When specified, this will allow for network statistics to be gathered and graphed on the frontend.

**Comment by jonstout** [comment]
SNMP options are as follows:
```
snmpv3:
    security_level: noAuthNoPriv|authNoPriv|authPriv
    auth_protocol: MD5|SHA
    auth_password: ''
    priv_protocol: DES|AES
    priv_password: ''
snmpv2:
    community: ''
```
